# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: Docs/conf.py

######################################################################
# Option 1: Use mamba
# https://github.com/readthedocs/readthedocs.org/issues/8424
# https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba
# As of 6 April 2022, this fails with
# Command killed due to timeout or excessive memory consumption

#build:
#  os: ubuntu-20.04
#  tools:
#    python: "mambaforge-4.10"

######################################################################
# Option 2: Use conda
build:
  # Needed for now instead for python 3.9
  # https://github.com/readthedocs/readthedocs.org/issues/7554
  image: testing
  apt_packages:
    - libcairo2-dev
    - libpango1.0-dev
    - ffmpeg

# Optionally declare the Python requirements required to build your docs
#
# Don't do this here if you use the "mambaforge-4.10" option above or you will get
# errors like
# Problem in your project's configuration. Invalid "python.version": expected one of ..., got 3.9
python:
   version: "3.9"


# Use conda
conda:
  environment: environment.yaml  

